### PR TITLE
Design updates

### PR DESCRIPTION
**Pull request by nwalters512**
* Updated much of the iconography to use the newer Material Design icons
* Changed toolbar to use white icons instead of the old gray
* Changed navigation drawer to highlight items in blue when they are selected
* Removed icons from the toolbar title (those are discouraged now)

### CODE REVIEW

**Comment by nwalters512** [comment]
I just tested search again, it's broken in the home activity. Don't merge yet.

**Comment by nwalters512** [comment]
Searching is now functional again, bending review, this is good to go.

**Comment by jonan** [comment]
Hi Nathan,
Sorry for the (very) late reply, I haven't had much time to dedicate to ForkHub lately.

I've merged a few of your commits from #124 and #125: 040b33aec3f741609cda5c87a2559135fad53885 and aa8cd141385ed582939dd0460b39097cf21d9e71.
The rest of the commits are quite hard to merge as they include various unrelated changes.

Please open new PRs with just one feature so they can be easily reviewed, discussed and merged.

I'm specially interested in the navigation drawer's highlighted items (they are pretty nice) and the SearchView.

Other commits are not going to be merged, like the one changing all the imports (lots of noise, and no real benefit) or the one adding the Material Design icons (I'm trying to use GitHub's when ever possible). In general, please create an issue to discuss your work before dedicating to much time to it, so you don't end up working on something that wont be merged.

Thanks for your efforts!

**Comment by nwalters512** [comment]
Sorry, I got a bit eager with all the changes! I can of course break them up into separate issues/PRs. I got  bored on a plane ride and just started fixing random stuff, which wasn't a smart move.

**Pull request closed without merging**
