### PR TITLE
Remove duplicated dependencies

### PR DESCRIPTION
**Pull request by choweiyuan**
Seems like okhttp and support-v4 are duplicated,  (see the ones in *), removing dups

01:08:40: Executing external task 'dependencies'...
Could not find ZipAlign task. Did you specify a signingConfig for the variation Release?
:app:dependencies

Project :app

compile - Classpath for compiling the main sources.
+--- com.android.support:appcompat-v7:23.0.1
|    \--- com.android.support:support-v4:23.0.1
|         \--- com.android.support:support-annotations:23.0.1
+--- com.squareup.picasso:picasso:2.5.2
+--- com.squareup.okhttp:okhttp:2.5.0
|    \--- com.squareup.okio:okio:1.6.0
+--- com.squareup.okhttp:okhttp-urlconnection:2.5.0
|    \--- com.squareup.okhttp:okhttp:2.5.0 (*)
+--- org.roboguice:roboguice:2.0
|    \--- com.google.inject:guice:3.0
|         +--- javax.inject:javax.inject:1
|         +--- aopalliance:aopalliance:1.0
|         \--- org.sonatype.sisu.inject:cglib:2.2.1-v20090111
|              \--- asm:asm:3.1
+--- com.google.code.gson:gson:2.4
+--- org.eclipse.mylyn.github:org.eclipse.egit.github.core:4.1.0.201509280440-r
+--- com.android.support:support-v4:23.0.1 (*)
+--- com.google.inject.extensions:guice-assistedinject:3.0
+--- com.viewpagerindicator:library:2.4.1
\--- :lib:

### CODE REVIEW

**Comment by jonan** [comment]
Please rebase your branches properly against current master so we can get rid of that merge commit. You can create a new pull request with the two commits if you prefer.

Thanks for your help

**Comment by choweiyuan** [comment]
Will try that sometime tonight. When you say the two commits, you mean this & the one about gson?

**Comment by jonan** [comment]
Yes, you can send both in the same pull request so you don't need to rebase both of them

**Comment by jonan** [comment]
I've rebased both pull requests and merge them.

Thanks :wink:

**Comment by choweiyuan** [comment]
Sorry I had a busy working week!  :+1: Will try and contribute more!

**Pull request closed without merging**
