### PR TITLE
fixed german translation

### PR DESCRIPTION
**Pull request by mueller-ma**
Added missing strings to values-de/strings.xml (why were they missing?)

Sry for that mess with newline commits.

### CODE REVIEW

**Comment by jonan** [comment]
Thanks for your contribution, are you planning on translating the remaining texts?
I don't want to merge the German translation with missing texts.

Also, please squash all your commits when they are ready.

**Comment by mueller-ma** [comment]
@jonan done
Can you add new strings to all strings.xml? It makes it much easier to translate the English strings, because you don't have to search for strings missing in values-de/strings.xml

**Comment by jonan** [comment]
Thanks for your contribution! :+1: 

Adding all strings to all languages is not desirable. You can always use the Translations Editor in Android Studio if you need to.

**Comment by mueller-ma** [comment]
@jonan I will give it a try. Currently I am using vimdiff

**Pull request merged**
