### PR TITLE
Correct extensions in CodeMirror for Clojure. Add Gradle too.

### PR DESCRIPTION
**Pull request by kenrestivo**
Added cljc, cljx, cljs, and edn extensions for Clojure language highlighting.
Also added gradle extension.

### CODE REVIEW

**Comment by liach** [comment]
Gradle is groovy, not Java.

**Comment by kenrestivo** [comment]
Fixed.

**Comment by jonan** [comment]
I'm not very fond of patching upstream projects.

Could you send your patch to https://github.com/codemirror/CodeMirror so we can import this fix with a simple upgrade?

**Comment by kenrestivo** [comment]
Done https://github.com/codemirror/CodeMirror/pull/3838

Note that the gradle and cljs were already upstream, the rest are submitted here.

**Comment by kenrestivo** [comment]
Upstream has merged the changes
https://github.com/codemirror/CodeMirror/commit/caed3308e3c406b911ed6ed9397fb92c3e92383e

**Pull request closed without merging**
